workflows:
  example-workflow:
    name: 3DObject Workflow
    scripts:
      - name: CICD Started
        script: echo "Hello Codemagician!"
    publishing:
      email:
        recipients:
          - yashpatel49000@gmail.com
