workflows:
  example-workflow:
    name: 3DObject Workflow
    scripts:
      - name: CICD Started
        script: echo "Hello Codemagician!"
      - name: Build project
        script: xcodebuild build -project "HelloPhotogrammetry.xcodeproj" -scheme "HelloPhotogrammetry" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      email:
        recipients:
          - yashpatel49000@gmail.com
